version: "3.9"
services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=mock-gen-db
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
