openapi: 3.0.1
info:
  title: "Api Mock Gen"
  description: "A simple API made to facilitate starting frontend projects for learning new frontend tech."
  version: 0.0.1
servers:
- url: http://localhost:3001/v1
tags:
- name: Tasks
  description: CRUD for Tasks
- name: Health Check
  description: Server Health CHeck
- name: Seed
  description: Generate Mock Data
paths:
  /health_check:
    get:
      tags:
      - Health Check Check
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: health_check
      parameters:
      - name: status
        in: query
        description: Status values that need to be considered for filter
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
            default: available
            enum:
            - available
            - pending
            - sold
      responses:
        "200":
          description: successful operation
          content: {}